
import java.awt.LayoutManager;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Tanjila Mawla Tania
 */
public class AddPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddPanel
     */
    
   

    public AddPanel() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stuNameLabel = new javax.swing.JLabel();
        regTextField = new javax.swing.JTextField();
        regLabel = new javax.swing.JLabel();
        stuNameTextField = new javax.swing.JTextField();
        batchLabel = new javax.swing.JLabel();
        stuNameTextField1 = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        addLabel = new javax.swing.JLabel();

        setLayout(null);

        stuNameLabel.setText("Student Name");
        add(stuNameLabel);
        stuNameLabel.setBounds(119, 100, 80, 29);
        add(regTextField);
        regTextField.setBounds(110, 55, 214, 29);

        regLabel.setText("Registration no");
        add(regLabel);
        regLabel.setBounds(120, 20, 80, 29);
        add(stuNameTextField);
        stuNameTextField.setBounds(110, 135, 214, 29);

        batchLabel.setText("Batch");
        add(batchLabel);
        batchLabel.setBounds(120, 175, 80, 29);
        add(stuNameTextField1);
        stuNameTextField1.setBounds(110, 215, 214, 29);

        addButton.setText("ADD");
        add(addButton);
        addButton.setBounds(190, 262, 53, 23);

        addLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/addLabelImage.png"))); // NOI18N
        add(addLabel);
        addLabel.setBounds(2, -1, 400, 300);
    }// </editor-fold>//GEN-END:initComponents
 public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              AddPanel studentEntryPanel = new AddPanel();
              studentEntryPanel.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JLabel addLabel;
    private javax.swing.JLabel batchLabel;
    private javax.swing.JLabel regLabel;
    private javax.swing.JTextField regTextField;
    private javax.swing.JLabel stuNameLabel;
    private javax.swing.JTextField stuNameTextField;
    private javax.swing.JTextField stuNameTextField1;
    // End of variables declaration//GEN-END:variables
}
