
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Tanjila Mawla Tania
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public static Connection conn = null;
    public static ResultSet rs = null;
    public static PreparedStatement pst = null;
    static Home home;
    static AddFrame addframe;

    public static void opendb() {
        try {
            try {
                Class.forName("org.sqlite.JDBC");
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }
            conn = DriverManager.getConnection("jdbc:sqlite:E:\\Study_new\\Project300\\SQLiteProject\\biometric.sqlite");
            System.out.println("connmain" + conn);
            //JOptionPane.showMessageDialog(null, "connect");
        } catch (SQLException ex) {
            Logger.getLogger(Adding.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public static void closedb() {

        try {
            conn.close();
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public Home() {
        System.out.println("print");
        initComponents();
        System.out.println("print1");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPanel = new javax.swing.JPanel();
        takeAttendanceButton = new javax.swing.JButton();
        studentEntryButton = new javax.swing.JButton();
        courseEntryButton = new javax.swing.JButton();
        addBatchToCourseButton = new javax.swing.JButton();
        addStudentToCourseButton = new javax.swing.JButton();
        fingerprintEntryButton = new javax.swing.JButton();
        deleteBatchFromCourseButton = new javax.swing.JButton();
        deleteStudentFromCourseButton = new javax.swing.JButton();
        menuLabel = new javax.swing.JLabel();
        homePanel = new javax.swing.JPanel();
        homeLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuPanel.setLayout(null);

        takeAttendanceButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        takeAttendanceButton.setForeground(new java.awt.Color(5, 5, 5));
        takeAttendanceButton.setText("Take Attendance");
        takeAttendanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                takeAttendanceButtonActionPerformed(evt);
            }
        });
        menuPanel.add(takeAttendanceButton);
        takeAttendanceButton.setBounds(60, 380, 190, 40);

        studentEntryButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        studentEntryButton.setForeground(new java.awt.Color(5, 5, 5));
        studentEntryButton.setText("Student Entry");
        studentEntryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentEntryButtonActionPerformed(evt);
            }
        });
        menuPanel.add(studentEntryButton);
        studentEntryButton.setBounds(60, 30, 190, 40);

        courseEntryButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        courseEntryButton.setForeground(new java.awt.Color(5, 5, 5));
        courseEntryButton.setText("Course Entry");
        courseEntryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseEntryButtonActionPerformed(evt);
            }
        });
        menuPanel.add(courseEntryButton);
        courseEntryButton.setBounds(60, 130, 190, 40);

        addBatchToCourseButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        addBatchToCourseButton.setForeground(new java.awt.Color(5, 5, 5));
        addBatchToCourseButton.setText("Add batch to course");
        addBatchToCourseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBatchToCourseButtonActionPerformed(evt);
            }
        });
        menuPanel.add(addBatchToCourseButton);
        addBatchToCourseButton.setBounds(60, 180, 190, 40);

        addStudentToCourseButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        addStudentToCourseButton.setForeground(new java.awt.Color(5, 5, 5));
        addStudentToCourseButton.setText("Add student to course");
        addStudentToCourseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentToCourseButtonActionPerformed(evt);
            }
        });
        menuPanel.add(addStudentToCourseButton);
        addStudentToCourseButton.setBounds(60, 230, 190, 40);

        fingerprintEntryButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        fingerprintEntryButton.setForeground(new java.awt.Color(5, 5, 5));
        fingerprintEntryButton.setText("Fingerprint Entry");
        fingerprintEntryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fingerprintEntryButtonActionPerformed(evt);
            }
        });
        menuPanel.add(fingerprintEntryButton);
        fingerprintEntryButton.setBounds(60, 80, 190, 40);

        deleteBatchFromCourseButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        deleteBatchFromCourseButton.setForeground(new java.awt.Color(5, 5, 5));
        deleteBatchFromCourseButton.setText("Delete batch from course");
        deleteBatchFromCourseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBatchFromCourseButtonActionPerformed(evt);
            }
        });
        menuPanel.add(deleteBatchFromCourseButton);
        deleteBatchFromCourseButton.setBounds(60, 280, 190, 40);

        deleteStudentFromCourseButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        deleteStudentFromCourseButton.setForeground(new java.awt.Color(5, 5, 5));
        deleteStudentFromCourseButton.setText("Delete student from course");
        deleteStudentFromCourseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteStudentFromCourseButtonActionPerformed(evt);
            }
        });
        menuPanel.add(deleteStudentFromCourseButton);
        deleteStudentFromCourseButton.setBounds(60, 330, 190, 40);

        menuLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menuLabelImage.jpg"))); // NOI18N
        menuPanel.add(menuLabel);
        menuLabel.setBounds(0, 0, 300, 500);

        homePanel.setPreferredSize(new java.awt.Dimension(400, 520));
        homePanel.setLayout(null);

        homeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homeLabelImage.png"))); // NOI18N
        homeLabel.setPreferredSize(new java.awt.Dimension(400, 520));
        homePanel.add(homeLabel);
        homeLabel.setBounds(0, 0, 400, 490);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(homePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(homePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studentEntryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentEntryButtonActionPerformed
        // TODO add your handling code here:

        home.getContentPane().removeAll();
        menuPanel.setBounds(400, 0, 300, 520);
        home.add(menuPanel);
        home.getContentPane().add(AddFrame.studentEntryPanel);
        home.repaint();
        home.setVisible(true);
    }//GEN-LAST:event_studentEntryButtonActionPerformed

    private void courseEntryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseEntryButtonActionPerformed
        // TODO add your handling code here:
        home.getContentPane().removeAll();
        menuPanel.setBounds(400, 0, 300, 520);
        home.add(menuPanel);
        home.getContentPane().add(AddFrame.courseEntryPanel);
        home.repaint();
        home.setVisible(true);
        
    }//GEN-LAST:event_courseEntryButtonActionPerformed

    private void addBatchToCourseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBatchToCourseButtonActionPerformed
        // TODO add your handling code here:
        home.getContentPane().removeAll();
        menuPanel.setBounds(400, 0, 300, 520);
        home.add(menuPanel);
        home.getContentPane().add(AddFrame.addBatchToCoursePanel);
        home.repaint();
        home.setVisible(true);
        
        
    }//GEN-LAST:event_addBatchToCourseButtonActionPerformed

    private void addStudentToCourseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentToCourseButtonActionPerformed
        // TODO add your handling code here:
        home.getContentPane().removeAll();
        menuPanel.setBounds(400, 0, 300, 520);
        home.add(menuPanel);
        home.getContentPane().add(AddFrame.addStudentToCoursePanel);
        home.repaint();
        home.setVisible(true);
    }//GEN-LAST:event_addStudentToCourseButtonActionPerformed

    private void takeAttendanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_takeAttendanceButtonActionPerformed
        // TODO add your handling code here:
        home.getContentPane().removeAll();
        menuPanel.setBounds(400, 0, 300, 520);
        home.add(menuPanel);
        home.getContentPane().add(AddFrame.takeAttendancePanel);
        home.repaint();
        home.setVisible(true);
    }//GEN-LAST:event_takeAttendanceButtonActionPerformed

    private void fingerprintEntryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fingerprintEntryButtonActionPerformed
        // TODO add your handling code here:
         String command = "D:\\MatlabI\\R2016b\\bin\\matlab.exe -nodisplay -nosplash -nodesktop -minimize -r \"run('E:\\Study_new\\Project300\\fingerprot\\B\\train_fprec');\"";
        try {
            Process process = Runtime.getRuntime().exec(command);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_fingerprintEntryButtonActionPerformed

    private void deleteBatchFromCourseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBatchFromCourseButtonActionPerformed
        // TODO add your handling code here:
        home.getContentPane().removeAll();
        menuPanel.setBounds(400, 0, 300, 520);
        home.add(menuPanel);
        home.getContentPane().add(AddFrame.deleteBatchFromCoursePanel);
        home.repaint();
        home.setVisible(true);
    }//GEN-LAST:event_deleteBatchFromCourseButtonActionPerformed

    private void deleteStudentFromCourseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteStudentFromCourseButtonActionPerformed
        // TODO add your handling code here:
        home.getContentPane().removeAll();
        menuPanel.setBounds(400, 0, 300, 520);
        home.add(menuPanel);
        home.getContentPane().add(AddFrame.deleteStudentFromCoursePanel);
        home.repaint();
        home.setVisible(true);
    }//GEN-LAST:event_deleteStudentFromCourseButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddFrame();
                home = new Home();
                home.setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBatchToCourseButton;
    private javax.swing.JButton addStudentToCourseButton;
    private javax.swing.JButton courseEntryButton;
    private javax.swing.JButton deleteBatchFromCourseButton;
    private javax.swing.JButton deleteStudentFromCourseButton;
    private javax.swing.JButton fingerprintEntryButton;
    private javax.swing.JLabel homeLabel;
    private javax.swing.JPanel homePanel;
    private javax.swing.JLabel menuLabel;
    public javax.swing.JPanel menuPanel;
    private javax.swing.JButton studentEntryButton;
    private javax.swing.JButton takeAttendanceButton;
    // End of variables declaration//GEN-END:variables
}
