DROP TABLE IF EXISTS "attendance";
CREATE TABLE "attendance" ("id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL UNIQUE  , "student_id" INTEGER NOT NULL , "course_id" INTEGER NOT NULL , "date" DATETIME NOT NULL , "attn" INTEGER NOT NULL ,FOREIGN KEY("student_id")  REFERENCES student("id"),FOREIGN KEY("course_id")  REFERENCES course("id"));
DROP TABLE IF EXISTS "course";
CREATE TABLE "course" ("id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL  UNIQUE, "code" VARCHAR NOT NULL  UNIQUE , "title" VARCHAR NOT NULL , "credit" DOUBLE NOT NULL );
DROP TABLE IF EXISTS "pivot";
CREATE TABLE "pivot" ("id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL  UNIQUE ,"student_id" INTEGER NOT NULL  , "course_id" INTEGER NOT NULL  ,FOREIGN KEY("student_id")  REFERENCES student("id"),FOREIGN KEY("course_id")  REFERENCES course("id") );
DROP TABLE IF EXISTS "student";
CREATE TABLE "student" ("id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL  UNIQUE , "reg" VARCHAR NOT NULL  UNIQUE , "stu_name" VARCHAR NOT NULL , "batch" INTEGER NOT NULL );
